"""Unisole Empower — Artifact & Document Generation (in-process MCP server)."""
from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path
from typing import Any

from fastmcp import Context, FastMCP

from core.config import settings
from core.storage import upload_artifact

SERVICE_NAME = "mcp-export"

logging.basicConfig(
    stream=sys.stderr, level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | mcp_export | %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(SERVICE_NAME)

mcp = FastMCP(name=SERVICE_NAME)


def _pop_context(kwargs: dict[str, Any]) -> tuple[str, str | None]:
    uid = kwargs.pop("_user_id", None)
    cid = kwargs.pop("_conversation_id", None)
    if not uid:
        raise PermissionError("Missing _user_id in tool call context")
    return uid, cid


def _tmp_workspace(user_id: str) -> Path:
    p = settings.tmp_path / user_id / "exports"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _nb_cell(cell_type: str, source: str) -> dict[str, Any]:
    base = {
        "cell_type": cell_type, "metadata": {},
        "source": [line + "\n" for line in source.splitlines()] or [""],
    }
    if cell_type == "code":
        base["execution_count"] = None
        base["outputs"] = []
    return base


def _notebook_skeleton(cells: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
            "unisole_empower": {"generated_at": int(time.time())},
        },
        "cells": cells,
    }


@mcp.tool
async def generate_jupyter_notebook(
    file_path: str, target_column: str, problem_type: str,
    ctx: Context,
    champion_model: str = "RandomForest",
    notebook_title: str | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    """Write a complete, runnable Jupyter notebook reproducing the AutoML pipeline."""
    user_id, conversation_id = _pop_context(kwargs)
    title = notebook_title or f"Unisole Empower — {file_path} AutoML Pipeline"
    await ctx.info(f"Composing notebook for {file_path}")
    await ctx.report_progress(10, 100, "Authoring markdown")

    if problem_type == "classification":
        if champion_model == "XGBoost":
            estimator_import = "from xgboost import XGBClassifier as Estimator"
        elif champion_model == "LightGBM":
            estimator_import = "from lightgbm import LGBMClassifier as Estimator"
        else:
            estimator_import = "from sklearn.ensemble import RandomForestClassifier as Estimator"
        metric_block = (
            "from sklearn.metrics import accuracy_score, f1_score, classification_report\n"
            "y_pred = pipe.predict(X_test)\n"
            "print('Accuracy:', accuracy_score(y_test, y_pred))\n"
            "print('F1 (weighted):', f1_score(y_test, y_pred, average='weighted', zero_division=0))\n"
            "print(classification_report(y_test, y_pred, zero_division=0))"
        )
    else:
        if champion_model == "XGBoost":
            estimator_import = "from xgboost import XGBRegressor as Estimator"
        elif champion_model == "LightGBM":
            estimator_import = "from lightgbm import LGBMRegressor as Estimator"
        else:
            estimator_import = "from sklearn.ensemble import RandomForestRegressor as Estimator"
        metric_block = (
            "from sklearn.metrics import mean_squared_error, r2_score\n"
            "import numpy as np\n"
            "y_pred = pipe.predict(X_test)\n"
            "print('RMSE:', float(np.sqrt(mean_squared_error(y_test, y_pred))))\n"
            "print('R^2 :', r2_score(y_test, y_pred))"
        )

    cells = [
        _nb_cell("markdown",
            f"# {title}\n\nGenerated by **Unisole Empower** — distributed MCP AutoML.\n\n"
            f"- **Dataset:** `{file_path}`\n- **Target:** `{target_column}`\n"
            f"- **Problem:** {problem_type}\n- **Champion:** {champion_model}\n"),
        _nb_cell("code",
            "import pandas as pd\nimport numpy as np\nimport joblib\nfrom pathlib import Path\n\n"
            "from sklearn.compose import ColumnTransformer\n"
            "from sklearn.impute import SimpleImputer\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.pipeline import Pipeline\n"
            "from sklearn.preprocessing import OneHotEncoder, StandardScaler\n"
            f"{estimator_import}\n\nRANDOM_STATE = 42"),
        _nb_cell("markdown", "## 1. Load Data"),
        _nb_cell("code",
            f"DATA_PATH = Path('{file_path}')\nTARGET = '{target_column}'\n"
            "df = pd.read_csv(DATA_PATH)\nprint('Shape:', df.shape)\ndf.head()"),
        _nb_cell("markdown", "## 2. Train/Test Split"),
        _nb_cell("code",
            "df = df.dropna(subset=[TARGET])\n"
            "y = df[TARGET]\nX = df.drop(columns=[TARGET])\n\n"
            + ("stratify = y if y.nunique() > 1 and y.value_counts().min() >= 2 else None\n"
               if problem_type == "classification" else "stratify = None\n")
            + "X_train, X_test, y_train, y_test = train_test_split(\n"
              "    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=stratify\n)"),
        _nb_cell("markdown", "## 3. Preprocessing Pipeline"),
        _nb_cell("code",
            "num_cols = X_train.select_dtypes(include='number').columns.tolist()\n"
            "cat_cols = X_train.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()\n\n"
            "num_pipe = Pipeline([('impute', SimpleImputer(strategy='median')),\n"
            "                     ('scale', StandardScaler())])\n"
            "cat_pipe = Pipeline([('impute', SimpleImputer(strategy='most_frequent')),\n"
            "                     ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])\n\n"
            "transformers = []\n"
            "if num_cols: transformers.append(('num', num_pipe, num_cols))\n"
            "if cat_cols: transformers.append(('cat', cat_pipe, cat_cols))\n"
            "pre = ColumnTransformer(transformers=transformers, remainder='drop')"),
        _nb_cell("markdown", f"## 4. Train Champion Model — {champion_model}"),
        _nb_cell("code",
            "model = Estimator(n_estimators=200, random_state=RANDOM_STATE, n_jobs=-1)\n"
            "pipe = Pipeline([('pre', pre), ('model', model)])\n"
            "pipe.fit(X_train, y_train)"),
        _nb_cell("markdown", "## 5. Evaluate"),
        _nb_cell("code", metric_block),
        _nb_cell("markdown", "## 6. Persist Artifact"),
        _nb_cell("code",
            "OUT = Path('champion_model.joblib')\njoblib.dump(\n"
            "    {'pipeline': pipe, 'feature_columns': X_train.columns.tolist(),\n"
            f"     'problem_type': '{problem_type}', 'target_column': TARGET}}, OUT\n)\n"
            "print('Saved to', OUT.resolve())"),
    ]

    nb = _notebook_skeleton(cells)
    await ctx.report_progress(70, 100, "Writing notebook")
    ts = int(time.time())
    stem = Path(file_path).stem.replace(" ", "_")
    nb_name = f"unisole_pipeline_{stem}_{ts}.ipynb"
    tmp_path = _tmp_workspace(user_id) / nb_name
    tmp_path.write_text(json.dumps(nb, indent=2), encoding="utf-8")

    await ctx.report_progress(90, 100, "Uploading notebook")
    artifact = upload_artifact(
        user_id=user_id, bucket=settings.BUCKET_EXPORTS,
        local_path=tmp_path, kind="training_notebook",
        conversation_id=conversation_id,
        metadata={"target_column": target_column, "problem_type": problem_type,
                  "champion_model": champion_model},
    )
    tmp_path.unlink(missing_ok=True)

    await ctx.report_progress(100, 100, "Notebook ready")
    return {
        "artifact_id": artifact.id,
        "notebook_file": artifact.filename,
        "notebook_url": artifact.signed_url,
        "download_url": artifact.signed_url,
        "n_cells": len(cells),
        "title": title,
    }


@mcp.tool
async def compile_pdf_report(
    project_title: str, file_path: str, target_column: str,
    leaderboard: list[dict[str, Any]], champion_model: str,
    ctx: Context, notes: str = "",
    **kwargs: Any,
) -> dict[str, Any]:
    """Compile a PDF summary report and upload to exports bucket."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    user_id, conversation_id = _pop_context(kwargs)
    await ctx.info("Composing PDF report")
    await ctx.report_progress(15, 100, "Initializing ReportLab")

    ts = int(time.time())
    stem = Path(file_path).stem.replace(" ", "_")
    pdf_name = f"unisole_report_{stem}_{ts}.pdf"
    tmp_path = _tmp_workspace(user_id) / pdf_name

    doc = SimpleDocTemplate(
        str(tmp_path), pagesize=LETTER,
        rightMargin=0.7*inch, leftMargin=0.7*inch,
        topMargin=0.7*inch, bottomMargin=0.7*inch,
    )
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("UnisoleH1", parent=styles["Heading1"], textColor=colors.HexColor("#0f172a"))
    h2 = ParagraphStyle("UnisoleH2", parent=styles["Heading2"], textColor=colors.HexColor("#4338ca"))
    body = styles["BodyText"]

    elements: list[Any] = [
        Paragraph("Unisole Empower", h1),
        Paragraph(project_title, h2),
        Spacer(1, 0.2*inch),
        Paragraph(f"<b>Dataset:</b> {file_path}", body),
        Paragraph(f"<b>Target Column:</b> {target_column}", body),
        Paragraph(f"<b>Champion Model:</b> {champion_model}", body),
        Paragraph(f"<b>Generated:</b> {time.strftime('%Y-%m-%d %H:%M:%S')}", body),
        Spacer(1, 0.3*inch),
        Paragraph("Leaderboard", h2),
    ]
    table_data = [["Rank", "Model", "CV Mean", "CV Std", "Primary Metric", "Train (s)"]]
    for idx, row in enumerate(leaderboard, 1):
        metric_key = row.get("metrics", {}).get("primary_metric", "—")
        metric_val = row.get("metrics", {}).get(metric_key) if metric_key != "—" else None
        table_data.append([
            str(idx), row.get("model", "—"),
            f"{row.get('cv_mean'):.4f}" if row.get("cv_mean") is not None else "—",
            f"{row.get('cv_std'):.4f}" if row.get("cv_std") is not None else "—",
            f"{metric_key}={metric_val:.4f}" if isinstance(metric_val, (int, float)) else "—",
            f"{row.get('train_seconds', '—')}",
        ])

    tbl = Table(table_data, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
        ("FONTSIZE", (0,0), (-1,-1), 9),
    ]))
    elements.append(tbl)
    elements.append(Spacer(1, 0.3*inch))

    if notes:
        elements.append(Paragraph("Notes", h2))
        elements.append(Paragraph(notes.replace("\n", "<br/>"), body))

    elements.append(Paragraph("Support", h2))
    elements.append(Paragraph("Reach out to <b>unisole.empower@gmail.com</b>.", body))

    await ctx.report_progress(75, 100, "Rendering PDF")
    doc.build(elements)

    await ctx.report_progress(92, 100, "Uploading PDF")
    artifact = upload_artifact(
        user_id=user_id, bucket=settings.BUCKET_EXPORTS,
        local_path=tmp_path, kind="pdf_report",
        conversation_id=conversation_id,
        metadata={"target_column": target_column, "champion_model": champion_model,
                  "leaderboard_rows": len(leaderboard)},
    )
    tmp_path.unlink(missing_ok=True)

    await ctx.report_progress(100, 100, "PDF saved")
    return {
        "artifact_id": artifact.id,
        "pdf_file": artifact.filename,
        "pdf_url": artifact.signed_url,
        "download_url": artifact.signed_url,
        "leaderboard_rows": len(leaderboard),
    }